#!/bin/bash

# GETME CLI MULTITASK COMMAND VERSION 1.0
# Comando creado por AdriJP

uname=$(whoami);
black="\033[1;30m";
red="\033[1;31m";
green="\033[1;32m";
brown="\033[1;33m";
blue="\033[1;34m";
purple="\033[1;35m";
cyan="\033[1;36m";
gray="\033[1;37m";
reset="\033[0m";

if [ "$1" = "--disk" ]
then

	diskinfo=$(df -h /);

	printf "${green}Datos de almacenamiento en disco\n";
	echo "${green}$diskinfo";
	printf "${reset}";

	exit 0;

elif [ "$1" = "--ram" ]
then

	raminfo=$(free -h);

	printf "${purple}Uso de la memoria RAM\n";
	printf "${purple}$raminfo\n";
	printf "${reset}";

	exit 0;

elif [ "$1" = "--cpu" ]
then

	cpuInfoRaw="/home/$uname/getme/cpu-info.txt";

	if [ -e $cpuInfoRaw ]
	then

		cpuInfo=$(sed -n '8, 13p' $cpuInfoRaw);

		printf "${blue}Datos de CPU:\n";
		printf "${blue}$cpuInfo\n";
		printf "\n";
		printf "${blue}Informacion de CPU guardada en:\n";
		printf "${blue}$cpuInfoRaw\n";
		printf "${reset}";

		exit 0;

	else

		lscpu > $cpuInfoRaw

		cpuInfo=$(sed -n '8, 13p' $cpuInfoRaw);

		printf "${blue}Datos de CPU:\n";
		printf "${blue}$cpuInfo\n";
		printf "\n";
		printf "${blue}Informacion de CPU guardada en:\n";
		printf "${blue}$cpuInfoRaw\n";
		printf "${reset}";

		exit 0;

	fi

elif [ "$1" = "--help" ]
then

	printf "${cyan}GETME CLI MULTITASK COMMAND VERSION O.9\n";
	printf "\n";
	printf "${cyan}				--- GUIA DE USO ---\n";
	printf "\n";
	printf "${cyan}		--cpu:		Muestra información sobre la CPU\n";
	printf "${cyan}		--ram:		Muestra el uso de la RAM\n";
	printf "${cyan}		--disk:		Muestra información sobre el disco duro\n";
	printf "\n";
	printf "${cyan}Ejecuta getme/mainrc sin argumentos o usando --version\n";
	printf "${cyan}para ver la version y los datos del programa\n";
	printf "${reset}";

	exit 0;

elif [ "$1" = "--version" ]
then

	printf "${cyan}GETME CLI MULTITASK COMMAND VERSION 1.0\n";

	exit 0;

elif [ "$1" = "" ]
then

	printf "${cyan}GETME CLI MULTITASK COMMAND VERSION O.9\n";
	printf "${cyan}Este comando necesita argumentos para operar\n";
	printf "${cyan}Introduce --help para ver una lista con las opciones del comando\n";
	printf "${reset}";

	exit 0;

else

	printf "${red}ERROR, ARGUMENTO DESCONOCIDO\n";
	printf "${red}Introduce --help para ver una lista con las opciones del comando\n";
	printf "${reset}";

	exit 1;

fi
